### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Kapeel** [tacorna/taco#13]
Hi,

I get the follwoing when I try to install taco.  Using Python 2.7

```
./taco_run -h
Traceback (most recent call last):
  File "taco/taco_run.py", line 8, in <module>
  File "/mctp/wkgrps/bioinfo/sw/Canopy/Canopy_64bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "taco/lib/run.py", line 13, in <module>
  File "/mctp/wkgrps/bioinfo/sw/Canopy/Canopy_64bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "taco/lib/aggregate.py", line 10, in <module>
  File "/mctp/wkgrps/bioinfo/sw/Canopy/Canopy_64bit/User/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIHzhNTD/taco.lib.pysam.cfaidx.so)
Failed to execute script taco_run
```
Thanks

Kapeel

**Comment by yniknafs** [comment]
Hello Kapeel,

Thanks for the message. It looks like you have an older version of GLIBC. So you will not be able to use our pre-packaged binary. 

I would recommend downloading the source code from [here](https://github.com/tacorna/taco/archive/v0.6.3.tar.gz). Unzip that tarball and run "./build.sh". This should build you the binaries that you can use to run taco and taco-refcomp. 

Note that currently, we are bundling a binary of CPAT that will probably also break because of the GLIBC issue. 

-Yashar

**Comment by yniknafs** [comment]
We have more instructions on building the code [here](http://tacorna.github.io/?start_page=build):
