### ISSUE TITLE
Compilation error when i build taco from source

### ISSUE THREAD

**Issue by upendrak** [tacorna/taco#14]
Hi, i am trying to build taco from source and i get errors when i run build.sh command. Can you let me know how to fix this..

```
Error compiling Cython file:
------------------------------------------------------------
...
FMT_STRING = '%s\t%d\t%d\t%f\n'
DEF C_FMT_STRING = "%s\t%d\t%d\t%f\n"

# Now declare the C function that requires a file:
cdef void c_write(FILE* fp, char* ref, int start, int end, FLOAT_DTYPE_t val):
    fprintf(fp, C_FMT_STRING, ref, start, end, val)
                           ^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:29:28: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).

Error compiling Cython file:
------------------------------------------------------------
...
    val = a[i]
    for j in xrange(1, alen):
        newval = a[j]
        if val != newval:
            if val != 0:
                fprintf(fp, C_FMT_STRING, ref, start + i, start + j, val)
                                       ^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:52:40: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).

Error compiling Cython file:
------------------------------------------------------------
...
            if val != 0:
                fprintf(fp, C_FMT_STRING, ref, start + i, start + j, val)
            i = j
            val = newval
    if val != 0:
        fprintf(fp, C_FMT_STRING, ref, start + i, start + alen, val)
                               ^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:56:32: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    main()
  File "setup.py", line 86, in main
    ext_modules=extensions + cythonize(cython_extensions),
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: taco/lib/cbedgraph.pyx
Traceback (most recent call last):
  File "/home/upendra/miniconda3/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1484, in build_tree
    config=config)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1065, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/utils.py", line 601, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/upendra/miniconda3/lib/python3.5/site-packages/conda_build/utils.py", line 597, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/upendra/miniconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/upendra/miniconda3/conda-bld/taco_1487465587056/work/taco-0.7.0/conda_build.sh']' returned non-zero exit status 1
```

**Comment by yniknafs** [comment]
Hello @upendrak. I think we've seen this before with old cython versions. You'll need Cython 0.23.4+. What cython version are you using? Try upgrading cython and building again. Hope this works. 

-Yashar

**Comment by upendrak** [comment]
Hi @yniknafs, i am using Cython version 0.25.2 and i guess that's the latest release of Cython. Let me know if there is anything else that i can do to fix this issue..

**Comment by yniknafs** [comment]
@upendrak can you give me details on what OS you are trying to build on? It also looks like you have modified the build script. What is different in `conda_build.sh` that wasn't in `build.sh`?

**Comment by HHHit** [comment]
@upendrak I also had a same problem, could you tell me what you did to fix it? Thanks!

**Comment by HHHit** [comment]
@yniknafs @upendrak When I want to run taco_run directly on the list, I got information below.
2017-09-14 10:47:44,717 pid=22741 ERROR - GTF file  not found
Traceback (most recent call last):
  File "taco/taco_run.py", line 57, in <module>
  File "taco/taco_run.py", line 25, in main
  File "taco/lib/run.py", line 411, in create
  File "taco/lib/base.py", line 152, in parse_tsv
taco.lib.base.TacoError: GTF file '' is not valid
Failed to execute script taco_run
I really don't know why, it seems that there are not many solutions on such problem in the Internet. Hopes you could help.

**Comment by sukanka** [comment]
Hello, I have a similar problem when building it from the source. The key issue is 
```
taco/lib/cbedgraph.pyx:10:0: 'dtypes/FLOAT_DTYPE_t.pxd' not found
```
And I don't know which dependency is missing, I searched it on google but few are useful.

Do you have any suggestion?

My build command is 
```bash
sed -i 's|cythonize(cython_extensions)|cythonize(cython_extensions, compiler_directives={"language_level": 3})|' setup.py
# we are building for python 3
python setup.py build
```
My environment:
```
cython 0.29.30-1
python 3.10.5-1
python-numpy 1.23.0-1
```

Below is the full log.
```bash
➜  taco git:(master) ✗ export LANG=C                                    
➜  taco git:(master) ✗ makepkg -sif   
==> Making package: taco 0.7.3-1 (Sat Jul 16 22:23:17 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found taco-0.7.3.tar.gz
==> Validating source files with sha256sums...
    taco-0.7.3.tar.gz ... Passed
==> Extracting sources...
  -> Extracting taco-0.7.3.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Compiling taco/lib/cbedgraph.pyx because it changed.
Compiling taco/lib/cchangepoint.pyx because it changed.
Compiling taco/lib/csuffixarray.pyx because it changed.
Compiling taco/lib/cpathfinder.pyx because it changed.
Compiling taco/lib/cbisect.pyx because it changed.
Compiling taco/lib/scipy/norm_sf.pyx because it changed.
Compiling taco/lib/pysam/cfaidx.pyx because it changed.
[1/7] Cythonizing taco/lib/cbedgraph.pyx

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as np
cimport cython

# import array type definitions
from dtypes import FLOAT_DTYPE
from dtypes cimport FLOAT_DTYPE_t
^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:10:0: 'dtypes.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as np
cimport cython

# import array type definitions
from dtypes import FLOAT_DTYPE
from dtypes cimport FLOAT_DTYPE_t
^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:10:0: 'dtypes/FLOAT_DTYPE_t.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# for print statement
FMT_STRING = '%s\t%d\t%d\t%f\n'
DEF C_FMT_STRING = "%s\t%d\t%d\t%f\n"

# Now declare the C function that requires a file:
cdef void c_write(FILE* fp, char* ref, int start, int end, FLOAT_DTYPE_t val):
                                                          ^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:28:59: 'FLOAT_DTYPE_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
cdef void c_write(FILE* fp, char* ref, int start, int end, FLOAT_DTYPE_t val):
    fprintf(fp, C_FMT_STRING, ref, start, end, val)


@cython.boundscheck(False)
def array_to_bedgraph(np.ndarray[FLOAT_DTYPE_t, ndim=1] a,
                                             ^
------------------------------------------------------------

taco/lib/cbedgraph.pyx:33:46: Invalid type.
Traceback (most recent call last):
  File "/tmp/makepkg/taco/src/taco-0.7.3/setup.py", line 94, in <module>
    main()
  File "/tmp/makepkg/taco/src/taco-0.7.3/setup.py", line 86, in main
    ext_modules=extensions + cythonize(cython_extensions, compiler_directives={"language_level": 3}),
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: taco/lib/cbedgraph.pyx
==> ERROR: A failure occurred in build().
    Aborting...
```
