### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by nongbaoting** [tacorna/taco#26]
2020-12-10 15:27:28,455 pid=72502 INFO - taco version 0.6.2
2020-12-10 15:27:28,455 pid=72502 INFO - ------------------------------------------------------------------------------
2020-12-10 15:27:28,455 pid=72502 INFO - verbose logging:                   False
2020-12-10 15:27:28,455 pid=72502 INFO - num processes:                     16
2020-12-10 15:27:28,455 pid=72502 INFO - output directory:                  taco_out
2020-12-10 15:27:28,455 pid=72502 INFO - filter min length:                 200
2020-12-10 15:27:28,455 pid=72502 INFO - filter min expression:             0.5
2020-12-10 15:27:28,455 pid=72502 INFO - filter splice juncs:               0
2020-12-10 15:27:28,455 pid=72502 INFO - additional splice motifs:
2020-12-10 15:27:28,455 pid=72502 INFO - reference genome FASTA file:       None
2020-12-10 15:27:28,455 pid=72502 INFO - reference GTF file:                None
2020-12-10 15:27:28,455 pid=72502 INFO - guided assembly mode:              False
2020-12-10 15:27:28,455 pid=72502 INFO - guided strand mode:                False
2020-12-10 15:27:28,455 pid=72502 INFO - guided ends mode:                  False
2020-12-10 15:27:28,455 pid=72502 INFO - GTF expression attribute:          FPKM
2020-12-10 15:27:28,455 pid=72502 INFO - isoform fraction:                  0.05
2020-12-10 15:27:28,455 pid=72502 INFO - max_isoforms:                      0
2020-12-10 15:27:28,455 pid=72502 INFO - assemble_unstranded:               0
2020-12-10 15:27:28,455 pid=72502 INFO - change point:                      True
2020-12-10 15:27:28,455 pid=72502 INFO - change point pvalue:               0.01
2020-12-10 15:27:28,455 pid=72502 INFO - change point fold change:          0.85
2020-12-10 15:27:28,455 pid=72502 INFO - change point trim:                 True
2020-12-10 15:27:28,455 pid=72502 INFO - path frac:                         0.0
2020-12-10 15:27:28,455 pid=72502 INFO - max paths:                         0
2020-12-10 15:27:28,456 pid=72502 INFO - Samples: 405
2020-12-10 15:27:28,456 pid=72502 INFO - Aggregating GTF files
2020-12-10 15:27:28,456 pid=72502 INFO - Aggregating in parallel using 16 processes
2020-12-10 15:34:09,005 pid=72502 INFO - Merging aggregated files
2020-12-10 15:34:38,785 pid=72502 INFO - Removing temporary files
2020-12-10 15:34:39,439 pid=72502 INFO - Aggregate done
2020-12-10 15:34:39,439 pid=72502 INFO - Indexing Loci
2020-12-10 15:34:44,198 pid=72502 INFO - Assembling GTF files
2020-12-10 15:34:44,198 pid=72502 INFO - Assembling in parallel using 16 processes
Process Process-26:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 114, in run
  File "taco/lib/assemble.py", line 494, in assemble_worker
  File "taco/lib/assemble.py", line 319, in assemble_locus
  File "taco/lib/assemble.py", line 263, in assemble_gene
  File "taco/lib/assemble.py", line 202, in assemble_isoforms
  File "taco/lib/path_graph.py", line 163, in create_optimal
  File "taco/lib/optimize.py", line 39, in maximize_bisect
  File "taco/lib/path_graph.py", line 153, in compute_kmers
  File "taco/lib/path_graph.py", line 125, in get_stats
ValueError: cannot convert float NaN to integer

**Comment by mkiyer** [comment]
This looks to me like atypical command-line parameters. Can you attach a small snippet of input file?
