### ISSUE TITLE
taco.lib.base.TacoError: GTF file 'Scaffold_25' is not valid

### ISSUE THREAD

**Issue by marco91sol** [tacorna/taco#27]
Hi, 

I run the folowing command: 

taco_run -p 32 -o annotation/taco_folder annotation/stringtie_first2.gtf

But, it blocks at  the beginning, giving me the following output  taco.lib.base.TacoError: GTF file 'Scaffold_25' is not valid

How can I solve it?

**Comment by mkiyer** [comment]
Hello -- we are doing some maintenance of taco. Can you attach a small piece of your GTF file please?

**Comment by isnmn** [comment]
Hello, I have the same issue. This is my head GTF:
```
head ps.gtf 
CM043852.1	StringTie	transcript	61810	63311	1000	.	.	gene_id "STRG.1"; transcript_id "STRG.1.1"; cov "476.077240"; FPKM "9.007406"; TPM "15.606282";
CM043852.1	StringTie	exon	61810	63311	1000	.	.	gene_id "STRG.1"; transcript_id "STRG.1.1"; exon_number "1"; cov "476.077240";
CM043852.1	StringTie	transcript	134808	135359	1000	.	.	gene_id "STRG.2"; transcript_id "STRG.2.1"; cov "10.246377"; FPKM "0.193862"; TPM "0.335886";
CM043852.1	StringTie	exon	134808	135359	1000	.	.	gene_id "STRG.2"; transcript_id "STRG.2.1"; exon_number "1"; cov "10.246377";
CM043852.1	StringTie	transcript	156800	188739	1000	+	.	gene_id "STRG.3"; transcript_id "STRG.3.1"; cov "1.410936"; FPKM "0.026695"; TPM "0.046252";
CM043852.1	StringTie	exon	156800	156929	1000	+	.	gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "1"; cov "1.253846";
CM043852.1	StringTie	exon	187663	188739	1000	+	.	gene_id "STRG.3"; transcript_id "STRG.3.1"; exon_number "2"; cov "1.429898";
CM043852.1	StringTie	transcript	170165	449773	1000	-	.	gene_id "STRG.4"; transcript_id "STRG.4.1"; cov "13.989768"; FPKM "0.264687"; TPM "0.458598";
CM043852.1	StringTie	exon	170165	174330	1000	-	.	gene_id "STRG.4"; transcript_id "STRG.4.1"; exon_number "1"; cov "14.481277";
CM043852.1	StringTie	exon	177437	177545	1000	-	.	gene_id "STRG.4"; transcript_id "STRG.4.1"; exon_number "2"; cov "15.339450";

```
This is my command:
`taco_run Transcriptome_stringtie.out.gtf  --filter-min-expr 0.1 --max-isoforms 1`

```
Error:
2023-08-29 13:28:24,736 pid=94982 ERROR - GTF file CM043852.1 not found
Traceback (most recent call last):
  File "taco/taco_run.py", line 57, in <module>
  File "taco/taco_run.py", line 25, in main
  File "taco/lib/run.py", line 411, in create
  File "taco/lib/base.py", line 152, in parse_tsv
taco.lib.base.TacoError: GTF file 'CM043852.1' is not valid
[94982] Failed to execute script taco_run
```


First it recognized the headers by stringtie (#'d out ones) so I removed those. But still gives the same error.
